server:
  port: 10001 # VPN 服务占用端口 10000 ，换为 10001
spring:
  application:
    name: eureka-bus
  rabbitmq:
    host: 192.168.235.104
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/