server:
  port: 8081
spring:
  application:
    name: my-health-invoker
eureka:
  client:
# 5秒抓一次服务的注册表
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/