server:
  port: 8899
spring:
  application:
    name: eureka-config-server
  profiles:
    active: subversion
# svn 使用svn协议访问而非https，与例子不同需要注意
  cloud:
    config:
      server:
        svn:
          uri: svn://192.168.235.104/config-project
          username: nanquanyuhao
          password: 12345
# 默认会在trunk目录下寻找配置文件
          default-label: eureka
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/