server:
  port: 8081
spring:
  application:
    name: ek-invoker
eureka:
  client:
# 每5秒去注册中心抓取服务列表，默认30秒
    registry-fetch-interval-seconds: 30
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: DEBUG